[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/static/*"
  [headers.values]
    Content-Type = "application/javascript"
