[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  condition = { Language = "en" }

[[headers]]
  for = "/static/*"
  [headers.values]
    Content-Type = "application/javascript"
